# Netlify configuration for GST Filing Automation Frontend

[build]
  # Build command
  command = "yarn build"
  
  # Directory with the static files
  publish = "build"
  
  # Environment variables
  [build.environment]
    NODE_VERSION = "18"

# SPA redirect for React Router
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Headers for security and performance
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    X-XSS-Protection = "1; mode=block"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.html"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"

[[headers]]
  for = "/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Enable HTTP/2 Server Push
[[headers]]
  for = "/"
  [headers.values]
    Link = "</static/css/main.*.css>; rel=preload; as=style, </static/js/main.*.js>; rel=preload; as=script"